name: Build Android

permissions:
  contents: write

env:
  APP_NAME: bevy_android

on:
  workflow_dispatch:
  push:
    paths-ignore:
      - ".github/build.yml"
      - ".github/build-**.yml"
      - ".github/release-**.yml"
      - "**/Makefile.toml"
      - "README.md"
    tags:
      - "v*"

jobs:
  ci:
    uses: ./.github/workflows/ci.yml

  native_build:
    container: sergioribera/rust-android:170-sdk-33
    needs: ci
    outputs:
      APP_NAME: ${{env.APP_NAME}}
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - uses: Swatinem/rust-cache@v2
      - name: Load .env file
        uses: xom9ikk/dotenv@v2
      - run: |
          echo "${{ secrets.KEYSTORE }}" | base64 --decode > ${{ env.APP_NAME }}.keystore
      # Start to build
      - name: build apk
        run: gradle assembleRelease -p launchers/mobile/android
      - name: build aab
        run: gradle bundleRelease -p launchers/mobile/android
      - name: Rename APK
        run: |
          cp launchers/mobile/android/build/outputs/apk/release/android-release-unsigned.apk ${{ env.APP_NAME }}.apk
          cp launchers/mobile/android/build/outputs/bundle/release/android-release.aab ${{ env.APP_NAME }}.aab
      - name: Sign Bundles
        run: |
          echo "${{ secrets.KEYSTORE_PASSWORD }}" | apksigner sign --ks ${{ env.APP_NAME }}.keystore --ks-key-alias ${{ env.APP_NAME }} ${{ env.APP_NAME }}.apk
          echo "${{ secrets.KEYSTORE_PASSWORD }}" | jarsigner -keystore ${{ env.APP_NAME }}.keystore ${{ env.APP_NAME }}.aab ${{ env.APP_NAME }}
      - name: Post Build | Upload Artifact
        uses: actions/upload-artifact@v3
        with:
          name: ${{ env.APP_NAME }}.apk
          path: ${{ env.APP_NAME }}.apk
      - name: Post Build | Upload aab Artifact
        uses: actions/upload-artifact@v3
        with:
          name: ${{ env.APP_NAME }}.aab
          path: ${{ env.APP_NAME }}.aab





